language: go

go:
  - 1.2
  - 1.4.1

install:
  - ./bin/install_deps.sh

script:
  - go get github.com/tools/godep
  - sudo cp /home/travis/gopath/bin/godep /usr/local/bin
  - sudo cp /home/travis/gopath/bin/protoc-gen-go /usr/local/bin
  - make all
