// Code generated by protoc-gen-go.
// source: DataSourceResponse.proto
// DO NOT EDIT!

package chevalier

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// obtained as a response from Vaultaire's readerd.
type DataSourceResponseBurst struct {
	Sources          []*DataSourceResponse `protobuf:"bytes,1,rep,name=sources" json:"sources,omitempty"`
	Error            *string               `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *DataSourceResponseBurst) Reset()         { *m = DataSourceResponseBurst{} }
func (m *DataSourceResponseBurst) String() string { return proto.CompactTextString(m) }
func (*DataSourceResponseBurst) ProtoMessage()    {}

func (m *DataSourceResponseBurst) GetSources() []*DataSourceResponse {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *DataSourceResponseBurst) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type DataSourceResponse struct {
	Source           []*DataSourceResponse_Tag `protobuf:"bytes,1,rep,name=source" json:"source,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *DataSourceResponse) Reset()         { *m = DataSourceResponse{} }
func (m *DataSourceResponse) String() string { return proto.CompactTextString(m) }
func (*DataSourceResponse) ProtoMessage()    {}

func (m *DataSourceResponse) GetSource() []*DataSourceResponse_Tag {
	if m != nil {
		return m.Source
	}
	return nil
}

type DataSourceResponse_Tag struct {
	Field            *string `protobuf:"bytes,1,req,name=field" json:"field,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataSourceResponse_Tag) Reset()         { *m = DataSourceResponse_Tag{} }
func (m *DataSourceResponse_Tag) String() string { return proto.CompactTextString(m) }
func (*DataSourceResponse_Tag) ProtoMessage()    {}

func (m *DataSourceResponse_Tag) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *DataSourceResponse_Tag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
}
